---
# Apply this to test group only
- hosts: test_group_2
  remote_user: pi
  become: yes
  tasks:
#  - debug: msg="Starting pi initial setup"
  - import_tasks: common_tasks/get_serial.yaml
    static: yes  
  - set_fact:
     rpi_serial: "{{ rpi_serial_output.stdout }}"
     rpi_configfile: "{{ lookup('ini', 'configfile section=' + rpi_serial_output.stdout + ' file=boards.ini')|quote }}"
  - debug: msg="Machine {{ inventory_hostname }} has actual hostname ({{ ansible_hostname }})"
  - debug: msg="Board serial is {{ rpi_serial }}"
  - debug: msg="Configuration file is {{ rpi_configfile }}"
  # Here, we dynamically include the task such that hostname is a parameter
  - include_tasks: common_tasks/set_hostname.yaml
    static: yes
    vars:
     desired_hostname = inventory_hostname
    when: ansible_hostname != inventory_hostname
  - import_tasks: common_tasks/restart_and_await.yaml
    static: yes
#  - import_tasks: common_tasks/update_apt_packages.yaml
#    static: yes
#  - import_tasks: common_tasks/restart_and_await.yaml
#    static: yes
  - debug: msg="Done updating apt, now prepping python"
  - import_tasks: common_tasks/install_pip_packages.yaml
    static: yes
