---
- name: base | setup | add master key
  authorized_key:
   user: pi
   state: present
   exclusive: True
   key: "{{ item }}"
  with_file:
   - ssh_keys/iotapi_master_1.pub
 
- name: base | setup | disable pass auth
  lineinfile: 
   path: /etc/ssh/sshd_config
   regexp: "^PasswordAuthentication"
   line: "PasswordAuthentication no"
   state: present
  notify: Restart ssh

- name: base | setup | disable root login
  lineinfile:
   path: /etc/ssh/sshd_config
   regexp: "^PermitRootLogin"
   line: "PermitRootLogin no"
   state: present
  notify: Restart ssh